name: Lint
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        name: Set up Python
        with:
          python-version: "3.10"
      - name: Install poetry
        run: python -m pip install poetry
      - name: Install dependencies
        run: python -m poetry install --only dev
      - name: Run linter
        run: python -m flake8 ./bento_service_registry ./tests
      - name: Run type checker
        run: python -m mypy bento_service_registry
